name: Build and Deploy OCI Image

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: francois2metz/steampipe-plugin-build-push-action@1bbcbf051ce210859a0e45cdea52ba41c4edd09a # v0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
